### ISSUE TITLE
in toBeStructure: HTML parser

### ISSUE THREAD

**Issue by goyyapazham** [goyyapazham/PartyLand#10]
it should see an input like:
"do the [insert noun] [insert verbs and other stuff]"
e.g.
"do the cows move"
"does the book listen attentively or squeamishly" 
as a "to be" question, but it doesn't, and the issue is with the HTML parser, which is, for some reason, making all nouns (plural and singular alike) unrecognizable to Kumar

**Comment by singhpardeep01** [comment]
what do you mean by "to be " question

**Comment by singhpardeep01** [comment]
you had your method check if the first word was "Do" but it didn't accept "do"
